ttskey: 阿里云的key ，和dashscope处配置的是一个key
#添加人类玩家开关
human_player: true
# 新结构：
llm_services:
  预言家:
    service: zhipuai
    api_key: xxxxxxx
    model_name: glm-4-plus
    temperature: 0.7
    voice:
      - sambert-zhinan-v1
    model_company: 智谱清言

  女巫:
    service: zhipuai
    api_key: xxxxxxx
    model_name: glm-4-plus
    temperature: 0.7
    voice:
      - sambert-zhiqi-v1
    model_company: 智谱清言
  狼人:
    service: deepseek
    api_key: xxxx
    model_name: deepseek-chat
    temperature: 0.7
    voice:
      - sambert-zhichu-v1
      - sambert-zhide-v1
      - sambert-zhijia-v1
    model_company: 深度求索
  猎人:
    service: dashscope
    api_key: xxxxxx
    model_name: qwen-turbo
    temperature: 0.7
    voice:
      - sambert-zhixiang-v1
    model_company: 阿里云百炼
  村民:
    service: dashscope
    api_key: xxxxxxx
    model_name: qwen-turbo
    temperature: 0.7
    voice:
      - sambert-zhiwei-v1
      - sambert-zhiming-v1
      - sambert-zhimo-v1
    model_company: 阿里云百炼
  # 其他角色默认配置
  default:
    service: dashscope
    api_key: sxxxxxx
    model_name: qwen-turbo
    temperature: 0.7
    voice: sambert-pingmin
    model_company: 阿里云百炼